/*
 * Copyright (c) 2019 Wanchain. All Rights Reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

const decoder = require("./decoder");
const {hexTrip0x, hexToAscii} = require("../../comm/lib");

const { xdr, scValToNative } = require("@stellar/stellar-sdk");

function get_nodes_of_sorobanMeta(transactionMeta) {
   const obj1 = transactionMeta[0].nodes[0];
   const result = obj1.nodes.filter(e => e.type === "sorobanMeta");
   if(result.length != 1) throw new Error("Invalid or unknown transaction");
  if(!result[0].nodes) {
    return [];
  }
   return result[0].nodes;
 }

function get_nodes_of_events(transactionMeta) {
  const nodes_of_sorobanMeta = get_nodes_of_sorobanMeta(transactionMeta);
  if(nodes_of_sorobanMeta.length === 0) {
    return [];
  }
  const result = nodes_of_sorobanMeta.filter(e => e.type === "events");
  if(result.length != 1) throw new Error("Invalid or unknown transaction");
  if(!result[0].nodes) {
    return [];
  }
  return result[0].nodes;
}

function get_all_events(result_meta_xdr) {
  const transactionMeta = decoder.decodeFromXDR(result_meta_xdr, "TransactionMeta");
  const event_info_list = get_nodes_of_events(transactionMeta);

  let process_finalEventNode = function (finalEventNode) {
    const contractId = (finalEventNode.nodes.filter( e => e.type === "contractId"))[0].value;
    const nodes_of_eventBody = (finalEventNode.nodes.filter( e => e.type === "body"))[0].nodes;
    if(nodes_of_eventBody.length != 1) throw new Error("Invalid or unknown transaction");

    const topics = nodes_of_eventBody[0].nodes[0];
    const data = nodes_of_eventBody[0].nodes[1];
    return {contractId, topics, data};
  }

  let events = event_info_list.map( evtInfo => process_finalEventNode(evtInfo));
  return events;
}

if(false){ //  test:

  var result_meta_xdr = 'AAAAAwAAAAAAAAACAAAAAwAJKU8AAAAAAAAAAMYnipCsdycKDtcKNZtugqex5iEs4B+KX8v09vI0N4irAAAAFydQgOoABeNVAAAA3AAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAMAAAAAAAkpSwAAAABmmOpiAAAAAAAAAAEACSlPAAAAAAAAAADGJ4qQrHcnCg7XCjWbboKnseYhLOAfil/L9PbyNDeIqwAAABcnUIDqAAXjVQAAAN0AAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAADAAAAAAAJKU8AAAAAZpjqeAAAAAAAAAABAAAABgAAAAMACSlLAAAABgAAAAAAAAAB3D9Nisi+X+Gv1tm1NAPlfH5+ZWsVH7nbyGVKsAqtxJYAAAAUAAAAAQAAABMAAAAA3XPU/69lXsAhMzKB4PhsP+z5MMv310gSTMcD9tr+Q9IAAAABAAAABgAAABAAAAABAAAAAQAAAA8AAAAFQWRtaW4AAAAAAAASAAAAAAAAAADGJ4qQrHcnCg7XCjWbboKnseYhLOAfil/L9PbyNDeIqwAAABAAAAABAAAAAQAAAA8AAAAHQkFTRVVSSQAAAAANAAAADXdhbi1zb3JvYmFuYToAAAAAAAAQAAAAAQAAAAIAAAAPAAAAB0JhbGFuY2UAAAAAEgAAAAAAAAAAxieKkKx3JwoO1wo1m26Cp7HmISzgH4pfy/T28jQ3iKsAAAAKAAAAAAAAAAAAAAAAAAAAAQAAABAAAAABAAAAAQAAAA8AAAAETWV0YQAAABEAAAABAAAAAgAAAA8AAAAEbmFtZQAAAA0AAAAIaG9yc2VORlQAAAAPAAAABnN5bWJvbAAAAAAADQAAAAVIT1JTRQAAAAAAABAAAAABAAAAAgAAAA8AAAAFT3duZXIAAAAAAAAKAAAAAAAAAAAAAAAAAABOIQAAABIAAAAAAAAAAMYnipCsdycKDtcKNZtugqex5iEs4B+KX8v09vI0N4irAAAAEAAAAAEAAAABAAAADwAAAAZTdXBwbHkAAAAAAAoAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAEACSlPAAAABgAAAAAAAAAB3D9Nisi+X+Gv1tm1NAPlfH5+ZWsVH7nbyGVKsAqtxJYAAAAUAAAAAQAAABMAAAAA3XPU/69lXsAhMzKB4PhsP+z5MMv310gSTMcD9tr+Q9IAAAABAAAABwAAABAAAAABAAAAAQAAAA8AAAAFQWRtaW4AAAAAAAASAAAAAAAAAADGJ4qQrHcnCg7XCjWbboKnseYhLOAfil/L9PbyNDeIqwAAABAAAAABAAAAAQAAAA8AAAAHQkFTRVVSSQAAAAANAAAADXdhbi1zb3JvYmFuYToAAAAAAAAQAAAAAQAAAAIAAAAPAAAAB0JhbGFuY2UAAAAAEgAAAAAAAAAAxieKkKx3JwoO1wo1m26Cp7HmISzgH4pfy/T28jQ3iKsAAAAKAAAAAAAAAAAAAAAAAAAAAAAAABAAAAABAAAAAgAAAA8AAAAHQmFsYW5jZQAAAAASAAAAAcalLo6HhB5Tatz8spcgqcVxsC6tqTsW+2HvGrHsoT22AAAACgAAAAAAAAAAAAAAAAAAAAEAAAAQAAAAAQAAAAEAAAAPAAAABE1ldGEAAAARAAAAAQAAAAIAAAAPAAAABG5hbWUAAAANAAAACGhvcnNlTkZUAAAADwAAAAZzeW1ib2wAAAAAAA0AAAAFSE9SU0UAAAAAAAAQAAAAAQAAAAIAAAAPAAAABU93bmVyAAAAAAAACgAAAAAAAAAAAAAAAAAATiEAAAASAAAAAcalLo6HhB5Tatz8spcgqcVxsC6tqTsW+2HvGrHsoT22AAAAEAAAAAEAAAABAAAADwAAAAZTdXBwbHkAAAAAAAoAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAMACSgvAAAABgAAAAAAAAABxqUujoeEHlNq3PyylyCpxXGwLq2pOxb7Ye8aseyhPbYAAAAUAAAAAQAAABMAAAAAzJzIXjph8q0ObgRC1z1Ma1N9LUdsPADX26znYersotsAAAABAAAAAwAAABAAAAABAAAAAQAAAA8AAAAFQWRtaW4AAAAAAAASAAAAAAAAAADGJ4qQrHcnCg7XCjWbboKnseYhLOAfil/L9PbyNDeIqwAAABAAAAABAAAAAQAAAA8AAAAHR2F0ZVdheQAAAAASAAAAAWN+5mnimAjqs3bWhULIq45NSqPDQMzB0W0Vozv6ndfGAAAAEAAAAAEAAAABAAAADwAAAAlQZWVyQ2hhaW4AAAAAAAARAAAAAQAAAAIAAAAPAAAADGV2bV9jaGFpbl9pZAAAAAsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE4gQAAAA8AAAAMZXZtX2NoYWluX3NjAAAADQAAABS7TpktqmpRhywVv5248HJiS5HTewAAAAAAAAABAAkpTwAAAAYAAAAAAAAAAcalLo6HhB5Tatz8spcgqcVxsC6tqTsW+2HvGrHsoT22AAAAFAAAAAEAAAATAAAAAMycyF46YfKtDm4EQtc9TGtTfS1HbDwA19us52Hq7KLbAAAAAQAAAAYAAAAQAAAAAQAAAAEAAAAPAAAABUFkbWluAAAAAAAAEgAAAAAAAAAAxieKkKx3JwoO1wo1m26Cp7HmISzgH4pfy/T28jQ3iKsAAAAQAAAAAQAAAAEAAAAPAAAAB0dhdGVXYXkAAAAAEgAAAAFjfuZp4pgI6rN21oVCyKuOTUqjw0DMwdFtFaM7+p3XxgAAABAAAAABAAAAAQAAAA8AAAAKT3JkZXJDb3VudAAAAAAACQAAAAAAAAAAAAAAAAAAAAEAAAAQAAAAAQAAAAIAAAAPAAAACE9yZGVyS2V5AAAADQAAACCAI7LMdHFKyOwwk3YIqr/ERn9sgs2zwQxNzb2Tpv4xpQAAABAAAAABAAAAAgAAABEAAAABAAAABwAAAA8AAAAFYnV5ZXIAAAAAAAASAAAAAAAAAADPoiZECls0DwAVJZ2ZAIOmhj8luOPuS5soArBprqpkDQAAAA8AAAAMbWVzc2FnZV90eXBlAAAADgAAAAtDcmVhdGVPcmRlcgAAAAAPAAAADG5mdF9jb250cmFjdAAAABIAAAAB3D9Nisi+X+Gv1tm1NAPlfH5+ZWsVH7nbyGVKsAqtxJYAAAAPAAAABm5mdF9pZAAAAAAACgAAAAAAAAAAAAAAAAAATiEAAAAPAAAABXByaWNlAAAAAAAACgAAAAAAAAAAAAAAAAAB4kAAAAAPAAAAC3ByaWNlX3Rva2VuAAAAAA0AAAAoQkI0RTk5MmRhQTZhNTE4NzJDMTVCZjlkYjhmMDcyNjI0YjkxRDM3QgAAAA8AAAAIcmVjaXBlbnQAAAANAAAAKEJCNEU5OTJkYUE2YTUxODcyQzE1QmY5ZGI4ZjA3MjYyNGI5MUQzN0IAAAASAAAAAAAAAADGJ4qQrHcnCg7XCjWbboKnseYhLOAfil/L9PbyNDeIqwAAABAAAAABAAAAAgAAAA8AAAAHT3JkZXJObwAAAAAJAAAAAAAAAAAAAAAAAAAAAQAAAA0AAAAggCOyzHRxSsjsMJN2CKq/xEZ/bILNs8EMTc29k6b+MaUAAAAQAAAAAQAAAAEAAAAPAAAACVBlZXJDaGFpbgAAAAAAABEAAAABAAAAAgAAAA8AAAAMZXZtX2NoYWluX2lkAAAACwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATiBAAAADwAAAAxldm1fY2hhaW5fc2MAAAANAAAAFLtOmS2qalGHLBW/nbjwcmJLkdN7AAAAAAAAAAMACSgrAAAABgAAAAAAAAABY37maeKYCOqzdtaFQsirjk1Ko8NAzMHRbRWjO/qd18YAAAAUAAAAAQAAABMAAAAA4V+sqzmJFjM0tyIDxqk3BEj+99nvLlDAO6uX3fTtupkAAAABAAAABwAAABAAAAABAAAAAQAAAA8AAAAHQ0hBSU5JRAAAAAALAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABX5EAAAAQAAAAAQAAAAEAAAAPAAAAFFNlY3AyNTZrMVB1YktleUNvdW50AAAACQAAAAAAAAAAAAAAAAAAAAQAAAAQAAAAAQAAAAIAAAAPAAAAEVNlY3AyNTZrMVB1YktleU5vAAAAAAAACQAAAAAAAAAAAAAAAAAAAAEAAAANAAAAQQSmEW5dgIBTqUj0+qwbhgSdBIOyIvb31iadH7/bOx5sP4LQwLyFch1m2dgnTWyIekWkP0BBbD1slnFHWTq6hKsEAAAAAAAAEAAAAAEAAAACAAAADwAAABFTZWNwMjU2azFQdWJLZXlObwAAAAAAAAkAAAAAAAAAAAAAAAAAAAACAAAADQAAAEEEYfHwRCi4onuTKeVHA5v9O3pjBj0rQNE2Be+bDg+/UZkP73X29wX4DKgAZ8iPlljQV+jNalqYbGfNBUMmSPl2EAAAAAAAABAAAAABAAAAAgAAAA8AAAARU2VjcDI1NmsxUHViS2V5Tm8AAAAAAAAJAAAAAAAAAAAAAAAAAAAAAwAAAA0AAABBBKYRbl2AgFOpSPT6rBuGBJ0Eg7Ii9vfWJp0fv9s7Hmw/gtDAvIVyHWbZ2CdNbIh6RaQ/QEFsPWyWcUdZOrqEqwQAAAAAAAAQAAAAAQAAAAIAAAAPAAAAEVNlY3AyNTZrMVB1YktleU5vAAAAAAAACQAAAAAAAAAAAAAAAAAAAAQAAAANAAAAQQRh8fBEKLiie5Mp5UcDm/07emMGPStA0TYF75sOD79RmQ/vdfb3BfgMqABnyI+WWNBX6M1qWphsZ80FQyZI+XYQAAAAAAAAEAAAAAEAAAABAAAADwAAAAlUaHJlc2hvbGQAAAAAAAAJAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAABAAkpTwAAAAYAAAAAAAAAAWN+5mnimAjqs3bWhULIq45NSqPDQMzB0W0Vozv6ndfGAAAAFAAAAAEAAAATAAAAAOFfrKs5iRYzNLciA8apNwRI/vfZ7y5QwDurl9307bqZAAAAAQAAAAgAAAAQAAAAAQAAAAEAAAAPAAAAB0NIQUlOSUQAAAAACwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAV+RAAAAEAAAAAEAAAACAAAADwAAAAVOT05DRQAAAAAAABEAAAABAAAABAAAAA8AAAAMZHN0X2NoYWluX2lkAAAACwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATiBAAAADwAAAA9zb3VyY2VfY2hhaW5faWQAAAAACwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAV+RAAAADwAAAA9zb3VyY2VfY29udHJhY3QAAAAAEgAAAAHGpS6Oh4QeU2rc/LKXIKnFcbAurak7Fvth7xqx7KE9tgAAAA8AAAAPdGFyZ2V0X2NvbnRyYWN0AAAAAA0AAAAUu06ZLapqUYcsFb+duPByYkuR03sAAAAJAAAAAAAAAAAAAAAAAAAAAQAAABAAAAABAAAAAQAAAA8AAAAUU2VjcDI1NmsxUHViS2V5Q291bnQAAAAJAAAAAAAAAAAAAAAAAAAABAAAABAAAAABAAAAAgAAAA8AAAARU2VjcDI1NmsxUHViS2V5Tm8AAAAAAAAJAAAAAAAAAAAAAAAAAAAAAQAAAA0AAABBBKYRbl2AgFOpSPT6rBuGBJ0Eg7Ii9vfWJp0fv9s7Hmw/gtDAvIVyHWbZ2CdNbIh6RaQ/QEFsPWyWcUdZOrqEqwQAAAAAAAAQAAAAAQAAAAIAAAAPAAAAEVNlY3AyNTZrMVB1YktleU5vAAAAAAAACQAAAAAAAAAAAAAAAAAAAAIAAAANAAAAQQRh8fBEKLiie5Mp5UcDm/07emMGPStA0TYF75sOD79RmQ/vdfb3BfgMqABnyI+WWNBX6M1qWphsZ80FQyZI+XYQAAAAAAAAEAAAAAEAAAACAAAADwAAABFTZWNwMjU2azFQdWJLZXlObwAAAAAAAAkAAAAAAAAAAAAAAAAAAAADAAAADQAAAEEEphFuXYCAU6lI9PqsG4YEnQSDsiL299YmnR+/2zsebD+C0MC8hXIdZtnYJ01siHpFpD9AQWw9bJZxR1k6uoSrBAAAAAAAABAAAAABAAAAAgAAAA8AAAARU2VjcDI1NmsxUHViS2V5Tm8AAAAAAAAJAAAAAAAAAAAAAAAAAAAABAAAAA0AAABBBGHx8EQouKJ7kynlRwOb/Tt6YwY9K0DRNgXvmw4Pv1GZD+919vcF+AyoAGfIj5ZY0FfozWpamGxnzQVDJkj5dhAAAAAAAAAQAAAAAQAAAAEAAAAPAAAACVRocmVzaG9sZAAAAAAAAAkAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAIAAAADAAkpTwAAAAAAAAAAxieKkKx3JwoO1wo1m26Cp7HmISzgH4pfy/T28jQ3iKsAAAAXJ1CA6gAF41UAAADdAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAwAAAAAACSlPAAAAAGaY6ngAAAAAAAAAAQAJKU8AAAAAAAAAAMYnipCsdycKDtcKNZtugqex5iEs4B+KX8v09vI0N4irAAAAFydpQmgABeNVAAAA3QAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAMAAAAAAAkpTwAAAABmmOp4AAAAAAAAAAEAAAAAAAAABAAAAAAAAAAB3D9Nisi+X+Gv1tm1NAPlfH5+ZWsVH7nbyGVKsAqtxJYAAAABAAAAAAAAAAMAAAAPAAAACHRyYW5zZmVyAAAAEgAAAAAAAAAAxieKkKx3JwoO1wo1m26Cp7HmISzgH4pfy/T28jQ3iKsAAAASAAAAAcalLo6HhB5Tatz8spcgqcVxsC6tqTsW+2HvGrHsoT22AAAACgAAAAAAAAAAAAAAAAAATiEAAAAAAAAAAcalLo6HhB5Tatz8spcgqcVxsC6tqTsW+2HvGrHsoT22AAAAAQAAAAAAAAABAAAADgAAAAtDcmVhdGVPcmRlcgAAAAAQAAAAAQAAAAIAAAANAAAAIIAjssx0cUrI7DCTdgiqv8RGf2yCzbPBDE3NvZOm/jGlAAAAEQAAAAEAAAAHAAAADwAAAAVidXllcgAAAAAAABIAAAAAAAAAAM+iJkQKWzQPABUlnZkAg6aGPyW44+5LmygCsGmuqmQNAAAADwAAAAxtZXNzYWdlX3R5cGUAAAAOAAAAC0NyZWF0ZU9yZGVyAAAAAA8AAAAMbmZ0X2NvbnRyYWN0AAAAEgAAAAHcP02KyL5f4a/W2bU0A+V8fn5laxUfudvIZUqwCq3ElgAAAA8AAAAGbmZ0X2lkAAAAAAAKAAAAAAAAAAAAAAAAAABOIQAAAA8AAAAFcHJpY2UAAAAAAAAKAAAAAAAAAAAAAAAAAAHiQAAAAA8AAAALcHJpY2VfdG9rZW4AAAAADQAAAChCQjRFOTkyZGFBNmE1MTg3MkMxNUJmOWRiOGYwNzI2MjRiOTFEMzdCAAAADwAAAAhyZWNpcGVudAAAAA0AAAAoQkI0RTk5MmRhQTZhNTE4NzJDMTVCZjlkYjhmMDcyNjI0YjkxRDM3QgAAAAAAAAABY37maeKYCOqzdtaFQsirjk1Ko8NAzMHRbRWjO/qd18YAAAABAAAAAAAAAAEAAAAOAAAAFkNyb3NzY2hhaW5GdW5jdGlvbkNhbGwAAAAAABAAAAABAAAABAAAAA0AAAAgOWjxgyaHSXVBLV11QCRGzGXhINq7cNndq467Sw6j3I8AAAALAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABOIEAAAANAAAAFLtOmS2qalGHLBW/nbjwcmJLkdN7AAAADQAAAmwAAAARAAAAAQAAAAMAAAAPAAAAD2NvbnRyYWN0QWRkcmVzcwAAAAASAAAAAcalLo6HhB5Tatz8spcgqcVxsC6tqTsW+2HvGrHsoT22AAAADwAAABBmdW5jdGlvbkNhbGxEYXRhAAAADQAAAcgAAAARAAAAAQAAAAIAAAAPAAAAC21lc3NhZ2VEYXRhAAAAAA0AAAF4AAAAEQAAAAEAAAAHAAAADwAAAAVidXllcgAAAAAAABIAAAAAAAAAAM+iJkQKWzQPABUlnZkAg6aGPyW44+5LmygCsGmuqmQNAAAADwAAAAxtZXNzYWdlX3R5cGUAAAAOAAAAC0NyZWF0ZU9yZGVyAAAAAA8AAAAMbmZ0X2NvbnRyYWN0AAAAEgAAAAHcP02KyL5f4a/W2bU0A+V8fn5laxUfudvIZUqwCq3ElgAAAA8AAAAGbmZ0X2lkAAAAAAAKAAAAAAAAAAAAAAAAAABOIQAAAA8AAAAFcHJpY2UAAAAAAAAKAAAAAAAAAAAAAAAAAAHiQAAAAA8AAAALcHJpY2VfdG9rZW4AAAAADQAAAChCQjRFOTkyZGFBNmE1MTg3MkMxNUJmOWRiOGYwNzI2MjRiOTFEMzdCAAAADwAAAAhyZWNpcGVudAAAAA0AAAAoQkI0RTk5MmRhQTZhNTE4NzJDMTVCZjlkYjhmMDcyNjI0YjkxRDM3QgAAAA8AAAALbWVzc2FnZUZ1bmMAAAAADwAAAAp3bWJSZWNlaXZlAAAAAAAPAAAACW5ldHdvcmtJZAAAAAAAAAsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFfkQAAAAAAAAABY37maeKYCOqzdtaFQsirjk1Ko8NAzMHRbRWjO/qd18YAAAABAAAAAAAAAAEAAAAOAAAAFE91dGJvdW5kVGFza0V4ZWN1dGVkAAAAEAAAAAEAAAAEAAAADQAAACA5aPGDJodJdUEtXXVAJEbMZeEg2rtw2d2rjrtLDqPcjwAAAAsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE4gQAAAA0AAAAUu06ZLapqUYcsFb+duPByYkuR03sAAAANAAACbAAAABEAAAABAAAAAwAAAA8AAAAPY29udHJhY3RBZGRyZXNzAAAAABIAAAABxqUujoeEHlNq3PyylyCpxXGwLq2pOxb7Ye8aseyhPbYAAAAPAAAAEGZ1bmN0aW9uQ2FsbERhdGEAAAANAAAByAAAABEAAAABAAAAAgAAAA8AAAALbWVzc2FnZURhdGEAAAAADQAAAXgAAAARAAAAAQAAAAcAAAAPAAAABWJ1eWVyAAAAAAAAEgAAAAAAAAAAz6ImRApbNA8AFSWdmQCDpoY/Jbjj7kubKAKwaa6qZA0AAAAPAAAADG1lc3NhZ2VfdHlwZQAAAA4AAAALQ3JlYXRlT3JkZXIAAAAADwAAAAxuZnRfY29udHJhY3QAAAASAAAAAdw/TYrIvl/hr9bZtTQD5Xx+fmVrFR+528hlSrAKrcSWAAAADwAAAAZuZnRfaWQAAAAAAAoAAAAAAAAAAAAAAAAAAE4hAAAADwAAAAVwcmljZQAAAAAAAAoAAAAAAAAAAAAAAAAAAeJAAAAADwAAAAtwcmljZV90b2tlbgAAAAANAAAAKEJCNEU5OTJkYUE2YTUxODcyQzE1QmY5ZGI4ZjA3MjYyNGI5MUQzN0IAAAAPAAAACHJlY2lwZW50AAAADQAAAChCQjRFOTkyZGFBNmE1MTg3MkMxNUJmOWRiOGYwNzI2MjRiOTFEMzdCAAAADwAAAAttZXNzYWdlRnVuYwAAAAAPAAAACndtYlJlY2VpdmUAAAAAAA8AAAAJbmV0d29ya0lkAAAAAAAACwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAV+RAAAAAQAAAAA='

  const events = get_all_events(result_meta_xdr);
  console.log(events);

  const finalEventData = get_events_data_by(events, "CBRX5ZTJ4KMAR2VTO3LIKQWIVOHE2SVDYNAMZQORNUK2GO72TXL4MDG5", ["CrosschainFunctionCall",])
  console.log("finalEventData size: ", finalEventData.length)
  finalEventData.forEach(evtData => {
    console.log("finalEventData: ", evtData)
    let timestamp = Date.now();
    timestamp = parseInt(timestamp / 1000);
    evtData.timestamp = timestamp;
    // console.log("functionCallData.messageData: ", evtData.functionCallData.messageData);
  })
  console.log("finalEventData: ", finalEventData);
}

/**
 *
 * @param events:  instance of {contractId, topics, data} structure, for example, the return by above 'get_all_events' method.
 * @param expected_contractId:  which contract emitted this event
 * @param expected_topics:      array of topic elements to match
 */
function get_events_data_by(events, expected_contractId, expected_topics) {
  let result = [];
  events.map(e => {
    if(e.contractId === expected_contractId) {
      const expectedTopicNum = expected_topics.length;
      const actualTopics = e.topics.nodes;

      let bTopicMatched = false;
      let matchedEventName = "";
      for(let i = 0; i < expectedTopicNum; i++) {
        if(expected_topics.includes(actualTopics[0].nodes[0].value)) {
          bTopicMatched = true;
          matchedEventName = actualTopics[0].nodes[0].value;
          break;
        }
      }

      if(!bTopicMatched) return;
      if(e.data.type !== "data" || e.data.value !== "[scvVec]") return

      const dataVec = e.data.nodes[0];
      const [taskIdNode, networkIdNode, contractAddressNode, finalFuncCallDataNode] = dataVec.nodes;

      const taskIdHexArrayStr = taskIdNode.nodes[0].value;
      const networkIdBigNum = networkIdNode.nodes[0].value;   // of peer chain
      const contractAddressHexArrayStr  = contractAddressNode.nodes[0].value;  // of peer chain
      const finalFuncCallDataHexArrayStr = finalFuncCallDataNode.nodes[0].value;

      let taskId = Buffer.from(JSON.parse(taskIdHexArrayStr)).toString("hex");
      const networkId = networkIdBigNum;

      let contractAddress = "";
      if(contractAddressNode.value === "[scvAddress]") { // Workaround approach
        // is a string --- dedicated to 'InboundTaskExecuted' event.
        taskId = hexToAscii(hexTrip0x(taskId));
        contractAddress = contractAddressHexArrayStr;
      }else{
        // is a buffer --- dedicated to 'OutboundTaskExecuted' event.
        contractAddress = Buffer.from(JSON.parse(contractAddressHexArrayStr)).toString(); // nft-market address;
      }

      result.push({
        event: matchedEventName, // event name, such as 'OutboundTaskExecuted', 'CrosschainFunctionCall'
        args:{
          "taskId" : taskId,
          "networkId": networkId,  // of peer chain
          "contractAddress": contractAddress, // on peer chain
          "functionCallData": finalFuncCallDataHexArrayStr,
        },
        })
    }
  })
  return result;
}

exports.eventParser = get_all_events;
exports.get_events_data_by = get_events_data_by;


