[package]
name = "message_bridge_interface"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
crate-type = ["rlib"]
doctest = false

[features]
testutils = []

[dependencies]
soroban-sdk = { workspace = true }

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }